name: Placate
favicon: null
layout_spectrum: 0.5862870309501886
typography_spectrum: 0.06858
title: Events that manage themselves
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070301'
    - '#7cb403'
    - '#cabdb3'
    - '#de0303'
    - '#04acb8'
  brandStrength: 0.9375
  lightness: 0.125
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
