name: Placate
favicon: null
layout_spectrum: 0.5862870309501886
typography_spectrum: 0.6846969099715352
title: Events that manage themselves
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.14123521628789604
  lightness: 0.21774723776616156
  saturation: 0.2284455995541066
  rhythmicContrast: 0.4264468909241259
purpose: []
